x-build-network: &build-network
  network: host

services:
  the-website:
    build:
      context: .
      dockerfile: the-website.Dockerfile
      <<: *build-network
      labels:
        com.docker.compose.project: ${COMPOSE_PROJECT_NAME:?Docker Compose Config Error! COMPOSE_PROJECT_NAME is not set!}
        com.docker.compose.service: the-website
    image: ${APP_NAME:?Docker Compose Config Error! APP_NAME is not set!}
    container_name: ${APP_NAME:?Docker Compose Config Error! APP_NAME is not set!}_instance
    ports:
      - "${APP_HOST_PORT:-8080}:${APP_PORT:-8080}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    profiles:
      - app
